server:
  port: 8001
spring:
  datasource:
    url: jdbc:oracle:thin:@123.57.247.171:1521:helowin
    username: A2018103726
    password: 364012
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*xml
